### ISSUE TITLE
colobar = 'nice' option broken for map_plot after the last TRamWAy updates

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#12]
Instead of adding a colorbar, the option now replaces the figure with the colorbar.

**Comment by francoislaurent** [comment]
I cannot reproduce the bug.

Any minimal example code?

**Comment by Alexander-Serov** [comment]
The issue seems to appear only on matplotlib 3.0.0. The code executes correctly on version 2.2.3. Still investigating.

**Comment by Alexander-Serov** [comment]
The issue is due to matplotlib 3.0.0. Should be fixed with the next update. In the meantime can use matplotlib 2.2.3
