### ISSUE TITLE
Feature suggestion: Allow to load trajectories from files with headers

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#14]
The current function load_xyt() does not allow for a simple way to drop or use headers.

**Comment by francoislaurent** [comment]
If argument *columns* is defined, then it always prevails and the header is ignored if any.
If a header is available at the first line of the file, column names are read from the header, unless argument *header* is ``False``.
To make *load_xyt* fail on missing header, set *header* to ``True``.
