### ISSUE TITLE
If map in map_plot is supplied as pd.Series, `path should not be a Series` error is raised

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#20]
This is unexpected behavior, and the error doesn't make sense.
In theory, there should not be any difference if one supplies scalar data as a DataFrame or a Series. As long as the index is correct, this should still result in a plot. Technically, supplying a 1D array as a pd.Series is more appropriate than supplying a DataFrame.

**Details:**

503         map_plot(map, cells=cells,
--> 504                  show=False, clip=False, colormap=colormap, alpha=alpha, linewidth=linewidth, figsize=figsize, dpi=dpi, aspect='equal', colorbar=colorbar, clim=clim)

tramway\tramway\helper\inference.py in map_plot(maps, cells, clip, output_file, fig_format, figsize, dpi, aspect, show, verbose, alpha, point_style, variable, segment, label, input_label, mode, title, **kwargs)
    728             label = input_label
    729         try:
--> 730             analyses = load_rwa(input_file, lazy=True)
    731             #if label:
    732             #       analyses = extract_analysis(analyses, label)

tramway\tramway\core\hdf5\store.py in load_rwa(path, verbose, lazy)
    128     """
    129     try:
--> 130         hdf = RWAStore(path, 'r', verbose=max(0, int(verbose) - 2) if verbose else False)
    131         #hdf._default_lazy = PermissivePeek
    132         hdf.lazy = lazy

tramway\tramway\core\hdf5\store.py in __init__(self, resource, mode, unload, verbose, **kwargs)
     35 
     36     def __init__(self, resource, mode='auto', unload=False, verbose=False, **kwargs):
---> 37         HDF5Store.__init__(self, resource, mode, verbose, **kwargs)
     38         self.unload = unload
     39         self.__special__ = {}

C:\Python37\lib\site-packages\rwa\hdf5.py in __init__(self, resource, mode, verbose, **kwargs)
    295 
    296     def __init__(self, resource, mode='auto', verbose=False, **kwargs):
--> 297         FileStore.__init__(self, hdf5_service, resource, mode=mode, verbose=verbose, **kwargs)
    298         self.lazy = False # for backward compatibility
    299 

C:\Python37\lib\site-packages\rwa\lazy.py in __init__(self, storables, resource, mode, **kwargs)
    219         self.temporary = None
    220         self.sane = True
--> 221         file_exists = os.path.isfile(resource)
    222         if self.writes(mode):
    223             dirname, basename = os.path.split(resource)

C:\Python37\lib\genericpath.py in isfile(path)
     28     """Test whether a path is a regular file"""
     29     try:
---> 30         st = os.stat(path)
     31     except OSError:
     32         return False

TypeError: stat: path should be string, bytes, os.PathLike or integer, not Series

**Comment by francoislaurent** [comment]
*pandas.Series* are now admitted by `map_plot` from release 0.3.5.
