### ISSUE TITLE
`dx`, `dy` are not used correctly in a standard Cell class

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#21]
One needs to use Sashas cell class instead of Translocations to correctly calculate inference in border cells. The current version should already handle `dx` and `dy` automatically, shouldn't it?

**Comment by francoislaurent** [comment]
Duplicate of issue #17. See commit https://github.com/DecBayComp/TRamWAy/commit/3729763e3c7b2d436650a3001e4c8b5a5021fd7c.
