### ISSUE TITLE
cell_index() method of Tessellation object claims to accept array-like point (location) coordinates, but throws an error on a 2D list

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#22]
It seems like it treats input as a numpy array and not an array-like object, since the error appears, when .shape is internally accessed.

**Comment by francoislaurent** [comment]
*list* objects are properly handled in `cell_index` from release 0.3.5.

On the other hand, the documentation was updated so that *pandas.DataFrame* objects only are now officially supported. This is aimed at simplifying code maintenance.
