### ISSUE TITLE
Gradient calculation sometimes returns arrays of 3 elements and sometimes of 2 elements

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#27]
And then fails to concatenate.

Run parameters:
np.random.seed(0)
tessellate(analysis_tree, 'kmeans', ref_distance=0, avg_location_count=5, initial='random', prune=False, label=label, strict_min_location_count=1)

infer(analysis_tree, 'd.conj_prior', input_label=mesh, output_label=snr_label, sigma=0.03)
RWA file:
[EXP01-01-BetaS403A-PRE-PP2-15ms_cluster_112.zip](https://github.com/DecBayComp/TRamWAy/files/3297579/EXP01-01-BetaS403A-PRE-PP2-15ms_cluster_112.zip)

Error message:

0%|          | 0/1 [00:00<?, ?it/s]WARNING:root:No tessellation found. Performing a standard kmeans_n_5 tessellation

Processing file: .\input\neuro-receptors\EXP01-01-BetaS403A-PRE-PP2-15ms_cluster_112.trxyt
<class 'pandas.core.frame.DataFrame'>
	'kmeans_n_5' <class 'tramway.tessellation.base.CellStats'>
		'snr' <class 'tramway.inference.base.Maps'>
			'bayes_factor' <class 'tramway.inference.base.Maps'>
.csv file not found. Skipping reading ksi
<Analyses <class 'pandas.core.frame.DataFrame'>>
Using  .\input\neuro-receptors\EXP01-01-BetaS403A-PRE-PP2-15ms_cluster_112.rwa
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-58-00c91fb2cd1b> in <module>()
      5     print(analysis_tree)
      6     calculate(csv_file=file, results_folder=results_path, bl_produce_maps=True,
----> 7               snr_label=snr_label, sigma=sigma, recalculate=recalculate, ticks=True, extension=extension, avg_location_count=5)

D:\Google Drive\git\Stochastic_Integrals_Diffusivity\ito-to-tramway\calculate.py in calculate(csv_file, results_folder, bl_produce_maps, snr_label, sigma, tessellation_parameters, verbose, recalculate, ticks, page_width_frac, min_diffusivity, extension, avg_location_count)
    130         if snr_label not in analysis_tree[mesh]:
    131             infer(analysis_tree, 'd.conj_prior', input_label=mesh, output_label=snr_label,
--> 132                   sigma=sigma)
    133             save_rwa(rwa_file, analysis_tree, force=True)
    134 

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\helper\inference.py in infer1(cells, mode, output_file, partition, verbose, localization_error, diffusivity_prior, potential_prior, jeffreys_prior, max_cell_count, dilation, worker_count, min_diffusivity, store_distributed, new_cell, new_group, constructor, include_empty_cells, cell_sampling, merge_threshold_count, grad, rgrad, priorD, priorV, input_label, output_label, comment, return_cells, profile, force, inplace, snr_extensions, **kwargs)
    398         min_diffusivity=min_diffusivity, localization_error=localization_error, \
    399         diffusivity_prior=diffusivity_prior, potential_prior=potential_prior, \
--> 400         jeffreys_prior=jeffreys_prior, rgrad=rgrad, snr_extensions=snr_extensions, **kwargs)
    401 
    402     helper.save_analyses(output_file, force=force)

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\helper\inference.py in infer(self, cells, worker_count, profile, min_diffusivity, localization_error, sigma, sigma2, diffusivity_prior, potential_prior, jeffreys_prior, rgrad, comment, verbose, snr_extensions, **kwargs)
    226         if rgrad:
    227             kwargs['rgrad'] = rgrad
--> 228         x = cells.run(getattr(self.module, self.setup['infer']), **kwargs)
    229 
    230         ret = {}

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\inference\base.py in run(self, function, *args, **kwargs)
    763         else:
    764             # direct function application
--> 765             result = function(self, *args, **kwargs)
    766 
    767         if returns:

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\inference\d_conj_prior.py in infer_d_conj_prior(cells, alpha, return_zeta_spurious, trust, **kwargs)
     98                 g_index.append(i)
     99                 g.append(gradD[np.newaxis, :])
--> 100         g = np.concatenate(g, axis=0)
    101         # zeta_spurious
    102         dt = cells[i].dt[0]  # `add_snr_extensions` checked that all dts are equal

ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by francoislaurent** [comment]
fix pulled into master.
