### ISSUE TITLE
Diffusivity gradient should not be calculated if a cell does not have neighbors

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#28]
It seems like the current implementation returns 0 if there are no neighbors. However, the diffusivity gradient is not defined in this case. I suggest returning NaN. Example attached.

![Culture1-BetaWT-PP2-45min-15ms_cluster_x=13 72_y=17 94_72_hexagon_g_dt_vec](https://user-images.githubusercontent.com/22743277/60016997-0c719600-9688-11e9-84d2-47f9c2a93628.png)

[Culture1-BetaWT-PP2-45min-15ms_cluster_x=13.72_y=17.94_72.rwa.zip](https://github.com/DecBayComp/TRamWAy/files/3320660/Culture1-BetaWT-PP2-45min-15ms_cluster_x.13.72_y.17.94_72.rwa.zip)

**Comment by francoislaurent** [comment]
fix available in master.
