### ISSUE TITLE
Feature suggestion: Identify outer layer cells in plots

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#7]
The following [piece of code](https://github.com/DecBayComp/Stochastic_Integrals_Diffusivity/blob/master/ito-to-tramway/get_exterior_cells.py) identifies the indices of the cells that form the outer layer in a tessellation scheme, i.e. are in contact with the 'outside'. It may be useful to know these cells so as not to plot in the final maps. To consider integrating into TRamWAy.

**Comment by francoislaurent** [comment]
The proposed approach did not address the following cases:

* two neighbour divergent cells may be separated by multiple closed cells, which does not make the 2-divergent-neighbour criterion adequate for identifying the closed cells that may extend far outside the data bounding box;
* two neighbour divergent cells may not be separated by any closed cell at all and, in this specific case, the 2-divergent-neighbour criterion selects closed cells that are clearly within the data bounding box; this is especially frequent at the corners.

The eventual approach makes use of a bounding box that - if not explicitly defined - is inferred from the location data, plus an optional margin.
