### ISSUE TITLE
RWA save error: AttributeError: `exposes` required for type: <class 'pandas.core.indexes.range.RangeIndex'>

### ISSUE THREAD

**Issue by Alexander-Serov** [DecBayComp/TRamWAy#9]
When saving a .rwa file:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Python37\lib\site-packages\rwa\hdf5.py in tryPokeAny(self, objname, obj, record, visited, _stack)
    377                     # raise any exception to skip till the except block
--> 378                     raise TypeError
    379             self.pokeNative(objname, obj, record)

TypeError: 

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
C:\Python37\lib\site-packages\rwa\generic.py in poke(self, objname, obj, record, visited, _stack)
    345                     self.pokeStorable(storable, objname, obj, record, visited=visited, \
--> 346                         _stack=_stack)
    347                 elif self.isNativeType(obj):

C:\Python37\lib\site-packages\rwa\generic.py in pokeStorable(self, storable, objname, obj, container, visited, _stack)
    258         #print((objname, storable.storable_type)) # debug
--> 259         storable.poke(self, objname, obj, container, visited=visited, _stack=_stack)
    260         try:

C:\Python37\lib\site-packages\rwa\generic.py in _poke(store, objname, obj, container, visited, _stack)
    485                 store.poke(iobjname, iobj, sub_container, visited=visited, \
--> 486                     _stack=_stack)
    487     return _poke

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\core\hdf5\store.py in poke(self, objname, obj, container, visited, _stack, unload)
     61                                         setattr(obj, obj.__fromlazy__(name), None)
---> 62                 HDF5Store.poke(self, objname, obj, container, visited=visited, _stack=_stack)
     63                 if unload is not None:

C:\Python37\lib\site-packages\rwa\hdf5.py in poke(self, objname, obj, container, visited, _stack)
    334             container = self.store
--> 335         FileStore.poke(self, objname, obj, container, visited=visited, _stack=_stack)
    336 

C:\Python37\lib\site-packages\rwa\lazy.py in poke(self, *args, **kwargs)
    274         self.sane = False
--> 275         obj = LazyStore.poke(self, *args, **kwargs)
    276         self.sane = True

C:\Python37\lib\site-packages\rwa\lazy.py in poke(self, objname, obj, record, *args, **kwargs)
     68     def poke(self, objname, obj, record, *args, **kwargs):
---> 69         GenericStore.poke(self, objname, lazyvalue(obj, deep=True), record, *args, **kwargs)
     70 

C:\Python37\lib\site-packages\rwa\generic.py in poke(self, objname, obj, record, visited, _stack)
    345                     self.pokeStorable(storable, objname, obj, record, visited=visited, \
--> 346                         _stack=_stack)
    347                 elif self.isNativeType(obj):

C:\Python37\lib\site-packages\rwa\generic.py in pokeStorable(self, storable, objname, obj, container, visited, _stack)
    258         #print((objname, storable.storable_type)) # debug
--> 259         storable.poke(self, objname, obj, container, visited=visited, _stack=_stack)
    260         try:

C:\Python37\lib\site-packages\rwa\generic.py in poke_dataframe(service, dfname, df, parent_container, visited, _stack)
   1232         service.poke('data', data, container, visited=visited, _stack=_stack)
-> 1233         service.poke('index', df.index, container, visited=visited, _stack=_stack)
   1234     peek_dataframe = unicode_columns(peek(pandas.DataFrame, ['data', 'index']))

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\core\hdf5\store.py in poke(self, objname, obj, container, visited, _stack, unload)
     61                                         setattr(obj, obj.__fromlazy__(name), None)
---> 62                 HDF5Store.poke(self, objname, obj, container, visited=visited, _stack=_stack)
     63                 if unload is not None:

C:\Python37\lib\site-packages\rwa\hdf5.py in poke(self, objname, obj, container, visited, _stack)
    334             container = self.store
--> 335         FileStore.poke(self, objname, obj, container, visited=visited, _stack=_stack)
    336 

C:\Python37\lib\site-packages\rwa\lazy.py in poke(self, *args, **kwargs)
    274         self.sane = False
--> 275         obj = LazyStore.poke(self, *args, **kwargs)
    276         self.sane = True

C:\Python37\lib\site-packages\rwa\lazy.py in poke(self, objname, obj, record, *args, **kwargs)
     68     def poke(self, objname, obj, record, *args, **kwargs):
---> 69         GenericStore.poke(self, objname, lazyvalue(obj, deep=True), record, *args, **kwargs)
     70 

C:\Python37\lib\site-packages\rwa\generic.py in poke(self, objname, obj, record, visited, _stack)
    350                     self.tryPokeAny(objname, obj, record, visited=visited, \
--> 351                         _stack=_stack)
    352                 # rewind the stack

C:\Python37\lib\site-packages\rwa\hdf5.py in tryPokeAny(self, objname, obj, record, visited, _stack)
    387                 raise TypeError("unsupported type {} for object '{}'".format(_type, objname))
--> 388             storable = self.defaultStorable(_type, agnostic=self.isAgnostic(_type))
    389             self.pokeStorable(storable, objname, obj, record, visited=visited, _stack=_stack)

C:\Python37\lib\site-packages\rwa\generic.py in defaultStorable(self, python_type, storable_type, version, **kwargs)
    453         self.storables.registerStorable(default_storable(python_type, \
--> 454                 version=version, storable_type=storable_type), **kwargs)
    455         return self.byPythonType(python_type, True).asVersion(version)

C:\Python37\lib\site-packages\rwa\generic.py in default_storable(python_type, exposes, version, storable_type, peek)
    801         if not exposes:
--> 802             raise AttributeError('`exposes` required for type: {!r}'.format(python_type))
    803     return Storable(python_type, key=storable_type, \

AttributeError: `exposes` required for type: <class 'pandas.core.indexes.range.RangeIndex'>

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-d52b139362b3> in <module>()
      1 # save to file
      2 
----> 3 save_rwa(rwa_file, analysis_tree, force=True)

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\core\hdf5\store.py in save_rwa(path, analyses, verbose, force, compress, append)
    157                         if verbose:
    158                                 print('writing file: {}'.format(path))
--> 159                         store.poke('analyses', analyses)
    160                 finally:
    161                         store.close()

d:\google drive\git\stochastic_integrals_diffusivity\ito-to-tramway\tramway\tramway\core\hdf5\store.py in poke(self, objname, obj, container, visited, _stack, unload)
     60                                 if obj._lazy.get(name, True):
     61                                         setattr(obj, obj.__fromlazy__(name), None)
---> 62                 HDF5Store.poke(self, objname, obj, container, visited=visited, _stack=_stack)
     63                 if unload is not None:
     64                         self.unload = previous

C:\Python37\lib\site-packages\rwa\hdf5.py in poke(self, objname, obj, container, visited, _stack)
    333         if container is None:
    334             container = self.store
--> 335         FileStore.poke(self, objname, obj, container, visited=visited, _stack=_stack)
    336 
    337     def pokeNative(self, objname, obj, container):

C:\Python37\lib\site-packages\rwa\lazy.py in poke(self, *args, **kwargs)
    273     def poke(self, *args, **kwargs):
    274         self.sane = False
--> 275         obj = LazyStore.poke(self, *args, **kwargs)
    276         self.sane = True
    277         return obj

C:\Python37\lib\site-packages\rwa\lazy.py in poke(self, objname, obj, record, *args, **kwargs)
     67 
     68     def poke(self, objname, obj, record, *args, **kwargs):
---> 69         GenericStore.poke(self, objname, lazyvalue(obj, deep=True), record, *args, **kwargs)
     70 
     71     def locator(self, record):

C:\Python37\lib\site-packages\rwa\generic.py in poke(self, objname, obj, record, visited, _stack)
    356         except Exception as e:
    357             if top_call:
--> 358                 raise _stack.exception(e)
    359             else:
    360                 raise

AttributeError: `exposes` required for type: <class 'pandas.core.indexes.range.RangeIndex'>
In: analyses
    |- _data
       |- index

**Comment by francoislaurent** [comment]
Please upgrade rwa-python and report any other rwa errors if any:
```
pip install --upgrade rwa-python>=0.8a1
```
